# Generated by Django 4.0.3 on 2022-05-12 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_reservefood'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservetable',
            name='seater',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (8, 8), (10, 10), (20, 20)]),
        ),
    ]
