# Generated by Django 4.0.3 on 2022-05-11 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('customer', '0002_tableorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='table',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.reservetable'),
        ),
    ]
