# Generated by Django 4.0.3 on 2022-05-12 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_reservefood'),
        ('customer', '0004_alter_customer_table_alter_tableorder_guests'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked', models.BooleanField()),
                ('food_quantity', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (10, 10), (20, 20)])),
                ('food', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.reservefood')),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='food',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.foodorder'),
        ),
    ]
