# Generated by Django 4.0.3 on 2022-05-12 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_foodorder_customer_food'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='food',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='table',
        ),
        migrations.AddField(
            model_name='foodorder',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.customer'),
        ),
        migrations.AddField(
            model_name='tableorder',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.customer'),
        ),
    ]
