# Generated by Django 4.0.3 on 2022-05-12 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_remove_customer_food_remove_customer_table_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tableorder',
            name='guests',
        ),
    ]
