# Generated by Django 4.0.3 on 2022-05-12 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_remove_tableorder_guests'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodorder',
            name='table',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.tableorder'),
        ),
    ]
