# Generated by Django 4.0.3 on 2022-05-14 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0011_remove_foodorder_food_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodorder',
            name='food_types',
            field=models.CharField(choices=[('nonveg', 'NonVeg'), ('veg', 'Veg'), ('soups', 'Soups'), ('drinks', 'Drinks')], max_length=40, null=True),
        ),
    ]
