# Generated by Django 4.0.3 on 2022-05-14 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0014_alter_foodorder_checked_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodorder',
            name='checked',
        ),
    ]
