# Generated by Django 4.0.3 on 2022-05-14 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0018_alter_foodorder_food_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodorder',
            name='checked',
            field=models.BooleanField(),
        ),
    ]
