# Generated by Django 4.0.3 on 2022-05-16 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0020_alter_foodorder_checked_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodorder',
            name='checked',
        ),
        migrations.RemoveField(
            model_name='foodorder',
            name='food_quantity',
        ),
    ]
