# Generated by Django 4.0.3 on 2022-05-16 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0022_foodorder_checked_foodorder_food_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodorder',
            name='checked',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
