# Generated by Django 4.0.3 on 2022-05-16 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_reservefood_food_type'),
        ('customer', '0024_alter_foodorder_food_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodorder',
            name='food',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.reservefood'),
        ),
    ]
