# Generated by Django 4.0.3 on 2022-05-18 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0025_alter_foodorder_food'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodorder',
            name='table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.tableorder'),
        ),
    ]
