# Generated by Django 4.0.3 on 2022-05-18 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0026_alter_foodorder_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodorder',
            name='address1',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AddField(
            model_name='foodorder',
            name='address2',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AddField(
            model_name='foodorder',
            name='city',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AddField(
            model_name='foodorder',
            name='state',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
