# Generated by Django 4.0.3 on 2022-05-18 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0027_foodorder_address1_foodorder_address2_foodorder_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodorder',
            name='pincode',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='mobile_number',
            field=models.PositiveIntegerField(),
        ),
    ]
