# Generated by Django 4.0.3 on 2022-05-20 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0029_parking_foodorder_parking'),
    ]

    operations = [
        migrations.AddField(
            model_name='parking',
            name='price',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
