# Generated by Django 4.0.3 on 2022-05-20 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0031_rename_number_parking_vehicle_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='parking',
            name='block',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
