# Generated by Django 4.0.3 on 2022-05-20 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0032_parking_block'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodorder',
            name='parking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.parking'),
        ),
    ]
