# Generated by Django 4.0.3 on 2022-05-31 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0033_alter_foodorder_parking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tableorder',
            name='customer',
        ),
        migrations.AddField(
            model_name='tableorder',
            name='customer',
            field=models.ManyToManyField(to='customer.customer'),
        ),
    ]
