# Generated by Django 4.0.3 on 2022-06-02 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0035_remove_tableorder_customer_tableorder_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tableorder',
            name='customer',
        ),
        migrations.AddField(
            model_name='tableorder',
            name='customer',
            field=models.ManyToManyField(to='customer.customer'),
        ),
    ]
