# Generated by Django 4.0.3 on 2022-06-02 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_reservefood_food_type'),
        ('customer', '0036_remove_tableorder_customer_tableorder_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tableorder',
            name='table',
        ),
        migrations.AddField(
            model_name='tableorder',
            name='table',
            field=models.ManyToManyField(to='core.reservetable'),
        ),
    ]
