# Generated by Django 4.0.3 on 2022-06-02 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_reservefood_food_type'),
        ('customer', '0037_remove_tableorder_table_tableorder_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tableorder',
            name='customer',
        ),
        migrations.AddField(
            model_name='tableorder',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.customer'),
        ),
        migrations.RemoveField(
            model_name='tableorder',
            name='table',
        ),
        migrations.AddField(
            model_name='tableorder',
            name='table',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.reservetable'),
        ),
    ]
