# Generated by Django 4.0.3 on 2022-06-03 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0039_alter_tableorder_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='tableorder',
            name='out_time',
            field=models.TimeField(null=True),
        ),
    ]
