# Generated by Django 4.0.3 on 2022-06-04 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0040_tableorder_out_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tableorder',
            name='seater',
            field=models.IntegerField(choices=[(2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (8, 8), (10, 10), (20, 20)], null=True),
        ),
    ]
