# Generated by Django 4.0.3 on 2022-06-04 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0042_tableorder_parking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tableorder',
            name='parking',
        ),
    ]
