# Generated by Django 4.0.3 on 2022-06-04 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0043_remove_tableorder_parking'),
    ]

    operations = [
        migrations.AddField(
            model_name='tableorder',
            name='pre_time',
            field=models.TimeField(null=True),
        ),
    ]
