# Generated by Django 4.0.3 on 2022-05-21 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chef', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chef',
            name='position',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
