# Generated by Django 4.0.3 on 2022-05-22 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chef', '0002_chef_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='chef',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
